"""add household_id to ingredients and role to user_household

Revision ID: 702a38ec4ee9
Revises: abd33ed630fc
Create Date: 2025-12-09 21:45:53.652191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702a38ec4ee9'
down_revision: Union[str, Sequence[str], None] = 'abd33ed630fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('household_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_index(op.f('ix_ingredients_household_id'), 'ingredients', ['household_id'], unique=False)
    op.create_foreign_key(None, 'ingredients', 'households', ['household_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_household', sa.Column('role', sa.String(length=20), server_default='member', nullable=False))
    op.add_column('user_household', sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_household', 'joined_at')
    op.drop_column('user_household', 'role')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_index(op.f('ix_ingredients_household_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=True)
    op.drop_column('ingredients', 'household_id')
    # ### end Alembic commands ###
